### ISSUE TITLE
custom shader output weirdness I can't explain.

### ISSUE THREAD

**Issue by gee-ell** [norihiro/obs-multisource-effect#5]
First off, super-awesome plugin, thanks.

I'm a long-time D3D GPU/shader programmer, so I know how this should work.  I'm trying to write a very simple custom shader, but the outputs are not what they should be.

To trouble-shoot it, I'm using your add.effect.  It outputs the two video sources correctly (added).

I now modify only PsDrawBare like this:

	float4 rgba0 = src0.Sample(def_sampler, vert_in.uv);
	float4 rgba1 = src1.Sample(def_sampler, vert_in.uv);
	return rgba0;

This should only output the first source.  It does.

OK, so this should output the other one right:

	float4 rgba0 = src0.Sample(def_sampler, vert_in.uv);
	float4 rgba1 = src1.Sample(def_sampler, vert_in.uv);
	return rgba1;

It doesn't.  It _still_ outputs the 1st source!  This makes absolutely no sense!  When I add (as you do), I get both sources added correctly!

	float4 rgba0 = src0.Sample(def_sampler, vert_in.uv);
	float4 rgba1 = src1.Sample(def_sampler, vert_in.uv);
	return rgba0 + rgba1;

The only way I can show the 2nd source if I remove the sampling of the first one:

```
//	float4 rgba0 = src0.Sample(def_sampler, vert_in.uv);
	float4 rgba1 = src1.Sample(def_sampler, vert_in.uv);
	return rgba1;
```
This shouldn't happen.  It's like a compiler bug.  It also breaks my custom shader, which is just using the RGB of one source and the alpha of the other.

BTW, it would be great if the plugin would reload and recompile the shader every time the users selects the file (so that changes to a custom shader get reloaded).  Right now it seems once loaded, the shader is cached & you have to restart OBS for shader file changes to take effect.

Or a 'Reload Shader' button in the UI would be even better.

**Comment by gee-ell** [comment]
re. reloading shaders, what I've done in the past is check the file modification date of the shader file, and if it has changed, automatically reload & recompile the shader - that way no user interaction is required.  That would be nice to have in OBS for shader developers.  And a display of compiler errors.

**Comment by gee-ell** [comment]
.. at first glance this is probably a bug in OBS' shader parser/compiler.  I've reported the issue to them:
https://github.com/obsproject/obs-studio/issues/5626

**Comment by norihiro** [comment]
I can reproduce the issue with step like below.

1. Copy `add.effect` to `a.effect`
2. Set `a.effect` as the effect file of this filter.
3. Modify `a.effect`
4. Set another effect file, then set `a.effect` again (which will trigger to reload the effect file.)

Then, old shader of `a.effect` works instead of the new shader.

I noticed the effect file is cached in OBS Studio, which causes old shader is loaded even if you modified your effect file.

https://github.com/obsproject/obs-studio/blob/b4cfc6bcf4c76228cc3e68899571888ff3a25386/libobs/graphics/graphics.c#L813-L815

It's annoying for those who debug effect file but that's how OBS Studio is implemented.
As a workaround, I'd like to suggest to change file name when you modified effect file.

**Comment by gee-ell** [comment]
Hi Norihiro,

yes it looks like the shader caching issue is in the OBS code, I can change that.

However the shader parsing issue (which produces the wrong pixel shader output) is a different issue, it seems to be a bug in OBS shader parser.

**Comment by norihiro** [comment]
> reloading shaders, what I've done in the past is check the file modification date of the shader file, and if it has changed, automatically reload & recompile the shader - that way no user interaction is required.

I just now implemented the `Reload` button but that would be better than the button.

> And a display of compiler errors.

The error is output to the log file. I want to keep the code of this plugin simple rather than providing rich feature for developers.
