### ISSUE TITLE
Blend function is not correctly implemented

### ISSUE THREAD

**Issue by norihiro** [norihiro/obs-multisource-effect#7]
Debugging this shader and noticed alpha channel is not correctly handled. https://github.com/obsproject/obs-studio/issues/5626#issuecomment-987488724

- `gs_blend_state_push` is called but `gs_blend_function` is not called.

**Comment by gee-ell** [comment]
I'm new to the obs source, but don't you also need gs_blend_state_pop() after a .. push()?

**Comment by norihiro** [comment]
Yes, I tried to write `pop` but wrongly wrote `reset`.

**Comment by norihiro** [comment]
I'm sorry for a lot of bugfixes.
Another commit 5f8f8b9 should fix the issue.

**Comment by gee-ell** [comment]
no problem, thanks for the updates!
