### ISSUE TITLE
Installation into Obs / CmakeLists.txt issue

### ISSUE THREAD

**Issue by gee-ell** [norihiro/obs-multisource-effect#8]
I might be doing this wrong, but I'm installing the plugin source into the OBS source by:

- checking it out to **obs-studio\plugins\obs-multisource-effect\**
- adding this to the end of **obs-studio\CMakeLists.txt**:
`add_subdirectory(plugins/obs-multisource-effect)`

There are then some problems with CMake Generate & Configure:

- **obs-multisource-effect/CMakeLists.txt** references **CMAKE_PROJECT_NAME** in many places.  However in this configuration, that resolves to the _parent_ project, ie "obs-studio", and so CMake Generate & Configure break.

replacing CMAKE_PROJECT_NAME with PROJECT_NAME (including in **plugin-macros.h.in**) resolves correctly to the plugin name.

https://cmake.org/cmake/help/latest/command/project.html

- however after CMake Configure & Build, in my MSVC 2019 project, the obs-multisource-effect project is not added to the 'plugins' group, but as its own project (I haven't figured out how to fix this).

- also, while the plugin builds correctly as part of the Obs build, it does not install automatically when the **CMakePredefinedTargets -> INSTALL** utility project is run (which copies all the files to the obs-studio folder in the Windows' **Program Files** folder).

it seems adding this to the end of **obs-multisource-effect/CMakeLists.txt** makes it install with the other files:

`install_obs_plugin_with_data(obs-multisource-effect data)`

**Comment by gee-ell** [comment]
actually there is a build issue as well:

the .c code cannot find
`#include "plugin-macros.generated.h"`

my workaround is to use
`#include "../../../build/plugins/obs-multisource-effect/src/plugin-macros.generated.h"`

**Comment by norihiro** [comment]
> checking it out to *obs-studio\plugins\obs-multisource-effect*

This plugin does not support to build inside the directory `obs-studio/plugins`.

`obs-multisource-effect` should be checked-out at outside the directory `obs-studio`.

When running `cmake`, options should be like below, where `%OBSPath% is the path to `obs-studio`.
```
cmake ^
-DLibObs_DIR="%OBSPath%\build64\libobs" ^
-DLIBOBS_INCLUDE_DIR="%OBSPath%\libobs" ^
-DLIBOBS_LIB="%OBSPath%\build64\libobs\%build_config%\obs.lib" ^
-DPTHREAD_LIBS="%OBSPath%\build64\deps\w32-pthreads\%build_config%\w32-pthreads.lib" ^
..
```
